# autogenerated by txs
#include:keyval
\CurrentOption#S
\MT#S
\MessageBreak#S
\PackageWarning{arg1}{arg2}#S
\lslig#S
\lslig{arg1}#S
\lsstyle#S
\pdfadjustspacing#S
\pdfoutput#S
\pdfprotrudechars#S
\pdftexrevision#S
\pdftexversion#S
\textls#S
\textls{arg1}#S
\textls{arg1}{arg2}#S
\\textls#S
