# autogenerated by txs
#include:listings
#include:xcolor
\framemargin#S
\inputpython{arg1}{arg2}{arg3}#S
\literatecolour#S
\pyth#S
\pythonprompt#S
\__hook listings#S
\__hook xcolor#S
\begin{python}
\end{python}
\sm#S
\tm#S
\unprocessedoptions-listings.sty#S
\unprocessedoptions-xcolor.sty#S
csnameendcsname#S
listings.sty#S
xcolor.sty#S
